### ISSUE TITLE
Titles added by search aren't handled correctly

### ISSUE THREAD

**Issue by pesky90** [NicoAiko/mikazuki#169]
If I search for an anime and try to add it via clicking the plus button, it seems to get added to the planned section.
When I go to the detailed section and select currently being watched and an episode count, nothing seems to happen.

**Comment by NicoAiko** [comment]
Unfortunately, the plus button on the search page currently behaves faulty.

Adding anime using the search page currently requires to enter the detail view of the anime and add it via the form.
