### ISSUE TITLE
No Login on own instance

### ISSUE THREAD

**Issue by Kadantte** [NicoAiko/mikazuki#192]
Hello!
After I installed all the app dep so the app is started without any problem but when I try to login with my Anilist.co account for some reason I can't get to work, of course, I create an app on my Anilist.co account Here's a link to test it if you want ofc [kadantte.moe](https://kadantte.moe).
Mikazuki preview:

![image](https://user-images.githubusercontent.com/11579313/88863550-00e18e80-d1fb-11ea-9b2a-d63a44a50f7d.png)

the App:

![image](https://user-images.githubusercontent.com/11579313/88863502-eb6c6480-d1fa-11ea-9efb-6d1289880976.png)

Auth request:

![image](https://user-images.githubusercontent.com/11579313/88863574-1656b880-d1fb-11ea-94a1-b740d66763d3.png)

After Anilist.co redirect me back:

![image](https://user-images.githubusercontent.com/11579313/88863608-27072e80-d1fb-11ea-8e1f-fbb00ee1c044.png)

Also, Anilist.co is saved my login to the app:

![image](https://user-images.githubusercontent.com/11579313/88863781-8a915c00-d1fb-11ea-98f1-a7701b98089b.png)

**Comment by NicoAiko** [comment]
The short answer would most likely be the redirect link.

I can give you a more accurate answer as soon as I am at my desk later.

**Comment by NicoAiko** [comment]
So, the redirect link, or `Redirect URL` as it is called in AniList should be something like this: 
`http://localhost:8080/#/aniList/?login` (replace the localhost stuff with your URL).
It is essential, that it ends on `/#/aniList/?login` as that's the parameter it needs to recognize your login.
You don't have to revoke the app's login authorization via AniList, I think, as it just will login without asking for your permission.

**Comment by Kadantte** [comment]
It fixed thank you so much.

![image](https://user-images.githubusercontent.com/11579313/88918920-32da0b80-d262-11ea-9a4a-7173c3b262fc.png)

**Comment by NicoAiko** [comment]
Just as a reminder: If you have other problems or questions, I'd recommend you check out the Mikazuki Discord server.
Might be faster to get in touch with me there.
