### ISSUE TITLE
Unable to scroll when on Special Thanks page

### ISSUE THREAD

**Issue by nattadasu** [NicoAiko/mikazuki#200]
**Describe the bug**
Visiting Special thanks page on settings and trying to scroll to the bottom (or very end) of page would result in scrolling was locked when "Support me on Ko-Fi" button appears.

**To Reproduce**
1. Open `Settings`
2. Click `Special Thanks`
3. Immediately scroll to bottom (very end) of page
4. Wait until "Support me on Ko-Fi" button appears, make sure it was 44px above page margin
5. Scroll to top with mouse wheel (or trackpad)

**Expected behavior**
Page should be scrollable, not locked

**Screenshots**
![image](https://user-images.githubusercontent.com/49780229/91703406-53b8b800-eba4-11ea-9275-5a186ed1c949.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.135

**Additional context**
- Clicking outside the dialog box and open settings page again, or clicking another setting pages (if reachable by small screen resolution) would resolve this issue.
- In some instances, the bug can be appears after "Support me on Ko-Fi" button. 
![image](https://user-images.githubusercontent.com/49780229/91704085-4fd96580-eba5-11ea-8f7c-cddad3153294.png)

**Comment by NicoAiko** [comment]
Should be fixed with 788c2adbf23303d1d6b619fccca94aa21ff7bfe4
