### ISSUE TITLE
Days Watched Progress Bar labels are incorrect

### ISSUE THREAD

**Issue by YDraig** [NicoAiko/mikazuki#202]
**Describe the bug**
The Labels above the progress bar for Days Watched are incorrect
it displays labels 0, **100**, 100 when over 50 days are watched.
(not sure when the autoscaling triggers to resize the graph)

**To Reproduce**
Steps to reproduce the behaviour:
1. Watch over 50 Days of Anime 
2. Go to Home
4. See error in Anime Stats Box

**Expected behaviour**
expected labels are 0, 50 ,100

**Screenshots**
![image](https://user-images.githubusercontent.com/1481748/92696900-ef5cdc00-f38d-11ea-92da-b3bfaeef1a97.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge-Chromium
 - Version 85.0.564.44

**Comment by NicoAiko** [comment]
Hm, I'll have to test this out, but thanks! I'll add this to v0.8.0 to fix it.
