### ISSUE TITLE
OAuth window won't work properly in Safari PWA for iOS

### ISSUE THREAD

**Issue by nattadasu** [NicoAiko/mikazuki#214]
**Describe the bug**
AniList authorization pop-up menu won't close automatically, and authorization cookie was "stuck" on auth window. Resulting in user was required to input their credential again, or using Mikazuki trough OAuth window.

**To Reproduce**
1. Open <https://mikazuki.moe> trough Safari.
2. Tap "Open application."
  a. Tap Share button
  b. Tap Add to Home Screen
  c. Configure your shortcut name, next tap "Add"
3. Open Mikazuki via new shortcut.
4. Tap Hamburger menu on left right, and then tap Settings. Go to AniList tab on settings pop-up.
5. Tap Login, and fill your credentials.

**Expected behavior**
An OAuth window should be closed automatically and saved your cookie to your PWA shortcut.

**Screenshots**
![image](https://user-images.githubusercontent.com/49780229/101952358-1fd14200-3c2b-11eb-80e3-ace7495a8b00.png)

**Smartphone (please complete the following information):**
 - Device: Apple iPhone 6
 - OS: iOS 12.4.9
 - Browser: Safari
 - Version: _Unknown_

**Additional context**
Note that I haven't deleted Website Data on Safari configuration. Also, yes, this is the most recent version, got update notice when iOS 14 was released for security patch.

**Comment by NicoAiko** [comment]
I can also recreate this on iOS 14.

Right now I don't have an answer to this.

Normally the browser would open AniList, and after successful login, redirect back.

Safari seems to open a WebView inside the browser itself and doesn't notice the redirection.

Unfortunately there is no workaround.

**Comment by nattadasu** [comment]
Hmmm.... I tried to make a shortcut again after Mikazuki update, and now working fine? ~~_ミラクル（ですか？） ✨_~~ 🤔

However I don't know for sure which one that "responsible" on this bug though.... 👀

Maybe because I did force deletion of website cache for "instant" version update, you did a bug fix, or its from AniList end problem resolved.

I'll close this issue then, might open it again if bug was found 😃👌
