### ISSUE TITLE
Missing language strings for translations

### ISSUE THREAD

**Issue by xLn2** [NicoAiko/mikazuki#216]
**Describe the bug**
Some strings has no language translation availability. I listed some of these which I found.

**To Reproduce**
- Missing string "Put on repeat list" for translation

1. Go to 'https://www.mikazuki.moe/application/#/aniList/completed'
2. Mouse over on 'Put on repeat list'
![image](https://user-images.githubusercontent.com/3073922/101981510-8f245180-3c7e-11eb-8d08-d6587d95fa0c.png)

*  Missing string "Revert to airing list" for translation
1. Go to 'https://www.mikazuki.moe/application/#/aniList/paused' & 'https://www.mikazuki.moe/application/#/aniList/dropped'
2. Mouse over on 'Revert to airing list'
![image](https://user-images.githubusercontent.com/3073922/101981547-c4c93a80-3c7e-11eb-902f-ff64f5dd0305.png)

* Missing string "You're currently not logged in! Please do so by clicking on the "Login" button below." translation
after logged of > settings > AniList > 
![image](https://user-images.githubusercontent.com/3073922/101981748-1625f980-3c80-11eb-9b8e-0c41c430764f.png)

* 'notifications.aniList.' Possible bug (might not english translation)
Go random anime i.e (https://www.mikazuki.moe/application/#/detail-view/249)
Change media status in these settings: Paused|Planning|Repeating|Dropped can cause 
![image](https://user-images.githubusercontent.com/3073922/101982082-acf3b580-3c82-11eb-80be-fabb8523b700.png)

**Desktop:**
 - OS: [Windows 10 2004 x64] 
 - Browser [Microsoft Edge]
 - Version [87.0.664.60 (64 bit)]

**Comment by NicoAiko** [comment]
I can confirm these.
The last one is not a translation issue but a bug in constructing the correct message though.

For adding the missing translations, I'll use a pull request though.
