### ISSUE TITLE
[Feature Request] Episodes Progress Bar

### ISSUE THREAD

**Issue by my3t** [NicoAiko/mikazuki#80]
I'd love to see a bar that dictates how many episodes of the anime has been aired, like the screenshot from Taiga below.

In this case, episode 8 was released and I have not watched it.

![image](https://user-images.githubusercontent.com/33184869/58535421-8bf27d80-8220-11e9-9841-5d9807dbc90c.png)

**Comment by NicoAiko** [comment]
Yes, I had this kind of bar in mind as well, though I have to think about how to implement it visually.

It's definitely on my watch and on the list of features to be release in v0.7.0.

**Comment by NicoAiko** [comment]
I would see this as low prioritized right now. It is not a bar, but you can see the remaining episodes that you have to watch as text here.

This kind of bar would be a custom component I'd have to create. In my opinion, this feature can be added at a later point.

![Bildschirmfoto 2019-12-20 um 17 49 13](https://user-images.githubusercontent.com/22343587/71270108-0f0c2a00-2351-11ea-9639-555321fb7a50.png)

**Comment by NicoAiko** [comment]
Working on this currently.
![image](https://user-images.githubusercontent.com/22343587/94350853-e4bf6980-0052-11eb-905f-a1f677394ba5.png)
